cross_target_platform:
  - osx-64
  - osx-arm64
macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
uname_machine:
  - x86_64
  - arm64
uname_kernel_release:
  - 13.4.0
  - 20.0.0
MACOSX_DEPLOYMENT_TARGET:  # [linux]
  - 10.9                   # [linux]
FINAL_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_x86_64_apple_darwin13_4_0
  - _sysconfigdata_arm64_apple_darwin20_0_0
zip_keys:
  - - cross_target_platform
    - macos_machine
    - uname_machine
    - uname_kernel_release
    - FINAL_PYTHON_SYSCONFIGDATA_NAME

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge,defaults
channel_targets:
  - conda-forge llvm_rc
