cross_target_platform:
  - linux-64       # [linux64]
  - linux-aarch64  # [linux and aarch64]
  - linux-s390x    # [linux and s390x]
  - osx-64         # [osx and x86_64]
  - osx-arm64      # [osx and arm64]
CBUILD:
  - x86_64-conda-linux-gnu       # [linux64]
  - aarch64-conda-linux-gnu      # [linux and aarch64]
  - s390x-conda-linux-gnu        # [linux and s390x]
  - x86_64-apple-darwin13.4.0    # [osx and x86_64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]
CHOST:
  - x86_64-conda-linux-gnu       # [linux64]
  - aarch64-conda-linux-gnu      # [linux and aarch64]
  - s390x-conda-linux-gnu        # [linux and s390x]
  - x86_64-apple-darwin13.4.0    # [osx and x86_64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]
uname_machine:
  - x86_64       # [linux and x86_64]
  - aarch64      # [linux and aarch64]
  - s390x        # [linux and s390x]
  - x86_64       # [osx and x86_64]
  - arm64        # [osx and arm64]
meson_cpu_family:
  - x86_64       # [linux and x86_64]
  - aarch64      # [linux and aarch64]
  - s390x        # [linux and s390x]
  - x86_64       # [osx and x86_64]
  - arm64        # [osx and arm64]
uname_kernel_release: # [osx]
  - 13.4.0  # [osx and x86_64]
  - 20.0.0  # [osx and arm64]
FINAL_PYTHON_SYSCONFIGDATA_NAME: # [osx]
  - _sysconfigdata_x86_64_apple_darwin13_4_0  # [osx and x86_64]
  - _sysconfigdata_arm64_apple_darwin20_0_0   # [osx and arm64]
