cross_target_platform:
  - osx-64
  - osx-arm64
macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-macos11
uname_machine:
  - x86_64
  - arm64
MACOSX_DEPLOYMENT_TARGET:
  - 10.9
  - 11.0
macos_min_version:
  - 10.9
  - 11.0
FINAL_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_x86_64_apple_darwin13_4_0
  - _sysconfigdata_arm64_apple_macos11
zip_keys:
  - - cross_target_platform
    - macos_machine
    - uname_machine
    - MACOSX_DEPLOYMENT_TARGET
    - macos_min_version
    - FINAL_PYTHON_SYSCONFIGDATA_NAME

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge,defaults
channel_targets:
  - conda-forge llvm_rc
