CBUILD:
  - x86_64-apple-darwin13.4.0    # [osx and x86_64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]

c_compiler:           # [osx]
  - clang_bootstrap   # [osx]
cxx_compiler:         # [osx]
  - clang_bootstrap   # [osx]

c_compiler_version:
  - 19.1.7              # [osx]
cxx_compiler_version:
  - 19.1.7              # [osx]

cross_target_platform:
  - osx-64     # [osx and x86_64]
  - osx-arm64  # [osx and arm64]
uname_machine:
  - x86_64  # [osx and x86_64]
  - arm64   # [osx and arm64]
meson_cpu_family:
  - x86_64  # [osx and x86_64]
  - aarch64 # [osx and arm64]
uname_kernel_release:
  - 13.4.0  # [osx and x86_64]
  - 20.0.0  # [osx and arm64]

FINAL_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_x86_64_apple_darwin13_4_0  # [osx and x86_64]
  - _sysconfigdata_arm64_apple_darwin20_0_0  # [osx and arm64]
