CBUILD:
  - x86_64-conda-linux-gnu       # [linux64]
  - aarch64-conda-linux-gnu      # [linux and aarch64]
  - x86_64-apple-darwin13.4.0    # [osx and x86_64]
  - arm64-apple-darwin20.0.0     # [osx and arm64]

MACOSX_DEPLOYMENT_TARGET:  # [linux]
  - 10.9                   # [linux]

version:
  - 17.0.6

# everything below is zipped
cross_target_platform:
  - osx-64     # [x86_64]
  - osx-arm64  # [not x86_64]
macos_machine:
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
uname_machine:
  - x86_64  # [x86_64]
  - arm64   # [not x86_64]
meson_cpu_family:
  - x86_64   # [x86_64]
  - aarch64  # [not x86_64]
uname_kernel_release:
  - 13.4.0  # [x86_64]
  - 20.0.0  # [not x86_64]
FINAL_PYTHON_SYSCONFIGDATA_NAME:
  - _sysconfigdata_x86_64_apple_darwin13_4_0  # [x86_64]
  - _sysconfigdata_arm64_apple_darwin20_0_0   # [not x86_64]
zip_keys:
  -
    - cross_target_platform
    - macos_machine
    - meson_cpu_family
    - uname_machine
    - uname_kernel_release
    - FINAL_PYTHON_SYSCONFIGDATA_NAME
